from enum import StrEnum


class UserRole(StrEnum):
    PLATFORM_ADMIN = "PLATFORM_ADMIN"
    CLUB_OWNER = "CLUB_OWNER"
    CLUB_OPERATOR = "CLUB_OPERATOR"
    PLAYER = "PLAYER"


class PaymentType(StrEnum):
    SINGLE_PAYER = "SINGLE_PAYER"
    SPLIT_PAYMENT = "SPLIT_PAYMENT"


class SlotStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    HOLD_SINGLE = "HOLD_SINGLE"
    HOLD_SPLIT = "HOLD_SPLIT"
    BOOKED = "BOOKED"
    BLOCKED = "BLOCKED"
    CANCELLED_BY_CLUB = "CANCELLED_BY_CLUB"
    COMPLETED = "COMPLETED"
    NO_SHOW = "NO_SHOW"


class BookingStatus(StrEnum):
    NEW = "NEW"
    PENDING_PAYMENT = "PENDING_PAYMENT"
    CONFIRMED = "CONFIRMED"
    EXPIRED = "EXPIRED"
    CANCELLED_BY_USER = "CANCELLED_BY_USER"
    CANCELLED_BY_CLUB = "CANCELLED_BY_CLUB"
    COMPLETED = "COMPLETED"
    NO_SHOW = "NO_SHOW"


class PaymentAttemptStatus(StrEnum):
    INITIATED = "INITIATED"
    GATEWAY_REDIRECTED = "GATEWAY_REDIRECTED"
    VERIFIED_SUCCESS = "VERIFIED_SUCCESS"
    FAILED_GATEWAY = "FAILED_GATEWAY"
    EXPIRED_UNPAID = "EXPIRED_UNPAID"
    LATE_SUCCESS_FLAGGED = "LATE_SUCCESS_FLAGGED"


class RefundStatus(StrEnum):
    INITIATED = "INITIATED"
    PENDING_GATEWAY = "PENDING_GATEWAY"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRY = "FAILED_RETRY"
    FAILED_ESCALATED = "FAILED_ESCALATED"


class WalletCreditStatus(StrEnum):
    OPT_IN_PENDING = "OPT_IN_PENDING"
    CREDITED = "CREDITED"
    CONSUMED_BOOKING = "CONSUMED_BOOKING"
    SUSPENDED_DISPUTE = "SUSPENDED_DISPUTE"


class SettlementStatus(StrEnum):
    PENDING_PERIOD = "PENDING_PERIOD"
    CALCULATED = "CALCULATED"
    ON_HOLD_DISPUTED = "ON_HOLD_DISPUTED"
    DISPATCHED_PAYA = "DISPATCHED_PAYA"
    SETTLED = "SETTLED"
    REJECTED_RETRY = "REJECTED_RETRY"
